### ISSUE TITLE
[Feat]: Compressed WASM package

### ISSUE THREAD

**Issue by TylerBloom** [SquireTournamentServices/SquireCore#132]
## Description:
Currently, the WASM module that is delivered for the webapp is uncompressed. While we have taken some steps to reduce the size of the WASM payload via compile-time optimizations, we can do better. It currently takes a few seconds to initially load into the webapp.

## The solution you'd like:
After compiling the WASM module, we should compress it (via something like `gz`). Locally, I have seen a massive reduction: going from a 5-6 MB file to a ~1.5 MB file.

## Alternatives:
While not exactly an alternative, we should pursue ways to reduce the size of the WASM module itself.

**Comment by CalebLItalien** [comment]
Looking into this!
